name: Deploy website

on: 
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy code
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to bastion host 
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.BASTION_HOST }}
        REMOTE_USER: ubuntu
        TARGET: /tmp/github-repo
    
    - name: SSH into WordPress server and copy files
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} ubuntu@${{ secrets.BASTION_HOST }} \
          "scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r /tmp/github-repo/* ubuntu@${{ secrets.WORDPRESS_HOST }}:/var/www/html"


