name: Deploy to AWS

on:
  push:
    branches:
      - main
    
  
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code 
        uses: actions/checkout@v2

      # - name: Create .ssh dir
      #   run: mkdir -p ~/.ssh

      - name: Add known hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> /home/runner/.ssh/known_hosts

      - name: Deploy to instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BASTION_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no -i ~/private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.WORDPRESS_HOST }} "
              #rm -rf /var/www/html/* 
              scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.WORDPRESS_HOST }}:/var/www/html/
            "
