name: Deploy website

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy code
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.BASTION_HOST }}
        REMOTE_USER: ubuntu
        TARGET: /var/www/html

    - name: SSH into WordPress server and copy files
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/private_key.pem ubuntu@${{ secrets.BASTION_HOST }} 'scp -o StrictHostKeyChecking=no -i ~/private_key.pem -r /home/ubuntu/1.txt ubuntu@${{ secrets.WORDPRESS_HOST }}:/var/www/html/'
